node_js:
  - 0.10

before_install:
  - phantomjs --version
  - npm --version

before_script:
  - npm install
  - npm install -g grunt-cli
  - npm install -g grunt-init

script: grunt travis --verbose --force
